import {
  type CompetitorProject,
  type GISLayer,
  type LandParcel,
  type MarketSignal,
  type RiskSignal,
} from "../domain/land-intelligence-types.js";

function polygonAround(
  latitude: number,
  longitude: number,
  latitudeDelta: number,
  longitudeDelta: number,
) {
  return [
    { latitude: latitude + latitudeDelta, longitude: longitude - longitudeDelta },
    { latitude: latitude + latitudeDelta * 0.8, longitude: longitude + longitudeDelta },
    { latitude: latitude - latitudeDelta, longitude: longitude + longitudeDelta * 0.9 },
    { latitude: latitude - latitudeDelta * 0.8, longitude: longitude - longitudeDelta },
  ];
}

export const sampleParcels: LandParcel[] = [
  {
    id: "AP-LAND-BNK-014",
    name: "พระราม 9 - รัชดา",
    geometry: polygonAround(13.7581, 100.5718, 0.0026, 0.0032),
    location: {
      subdistrict: "บางกะปิ",
      district: "ห้วยขวาง",
      province: "กรุงเทพฯ",
      coordinates: { latitude: 13.7581, longitude: 100.5718 },
      nearestTransitStation: "MRT พระราม 9",
      strategicCorridor: "CBD East",
      metroZone: "innerBangkok",
    },
    site: {
      areaRai: 7.8,
      areaSqWah: 3120,
      frontageMeters: 84,
      roadWidthMeters: 16,
      shapeEfficiencyScore: 86,
      ownershipComplexity: "multipleCooperativeOwners",
    },
    planning: {
      zoningCode: "พ.5",
      zoningDescription: "พาณิชยกรรมหนาแน่นสูง",
      far: 8,
      buildabilityScore: 88,
      infrastructureReadinessScore: 84,
      allowableProductTypes: ["condominium", "mixedUse", "homeOfficeRetail"],
      gisLayerIds: ["zoning-bkk-commercial", "transit-mrt-blue"],
    },
    accessibility: {
      distanceToMassTransitMeters: 520,
      distanceToExpresswayKm: 1.8,
      distanceToCbdKm: 5.4,
      driveTimeToCbdMinutes: 18,
    },
    market: {
      primaryCatchment: "Rama 9 CBD, Ratchada, Huai Khwang",
      targetSegments: ["upperMid", "premium"],
      estimatedResidentialPricePerSqm: 172000,
      demandDepthScore: 90,
    },
    financials: {
      askingPricePerSqWah: 493000,
      targetLandCostPerSqWah: 520000,
      estimatedGrossMarginPct: 31,
      capexComplexityScore: 74,
    },
    risk: {
      flood: "low",
      legal: "medium",
      environmental: "low",
      communityPolitical: "medium",
      criticalFlags: ["ต้องยืนยันภาระจำยอมทางเข้า"],
    },
    controlStatus: "underOption",
    tags: ["transit-led", "high-rise", "executive-shortlist"],
  },
  {
    id: "AP-LAND-BNK-022",
    name: "บางนา - ลาซาล",
    geometry: polygonAround(13.6653, 100.6268, 0.0035, 0.0037),
    location: {
      district: "บางนา",
      province: "กรุงเทพฯ",
      coordinates: { latitude: 13.6653, longitude: 100.6268 },
      nearestTransitStation: "BTS แบริ่ง",
      strategicCorridor: "Eastern Gateway",
      metroZone: "outerBangkok",
    },
    site: {
      areaRai: 12.4,
      areaSqWah: 4960,
      frontageMeters: 72,
      roadWidthMeters: 12,
      shapeEfficiencyScore: 81,
      ownershipComplexity: "singleOwner",
    },
    planning: {
      zoningCode: "ย.7",
      zoningDescription: "ที่อยู่อาศัยหนาแน่นปานกลาง",
      far: 4.5,
      buildabilityScore: 84,
      infrastructureReadinessScore: 86,
      allowableProductTypes: ["townhome", "mixedUse", "homeOfficeRetail"],
      gisLayerIds: ["zoning-bkk-residential", "future-transit-yellow"],
    },
    accessibility: {
      distanceToMassTransitMeters: 1180,
      distanceToExpresswayKm: 2.6,
      distanceToCbdKm: 14.2,
      driveTimeToCbdMinutes: 33,
    },
    market: {
      primaryCatchment: "Bangna, Bearing, Lasalle, Mega Bangna",
      targetSegments: ["midMarket", "upperMid"],
      estimatedResidentialPricePerSqm: 118000,
      demandDepthScore: 84,
    },
    financials: {
      askingPricePerSqWah: 258000,
      targetLandCostPerSqWah: 282000,
      estimatedGrossMarginPct: 29,
      capexComplexityScore: 82,
    },
    risk: {
      flood: "medium",
      legal: "low",
      environmental: "low",
      communityPolitical: "low",
    },
    controlStatus: "opportunity",
    tags: ["low-rise", "mixed-use", "east-growth"],
  },
  {
    id: "AP-LAND-NPT-006",
    name: "ศาลายา - พุทธมณฑล",
    geometry: polygonAround(13.798, 100.3266, 0.005, 0.006),
    location: {
      district: "นครชัยศรี",
      province: "นครปฐม",
      coordinates: { latitude: 13.798, longitude: 100.3266 },
      strategicCorridor: "West Growth",
      metroZone: "periUrban",
    },
    site: {
      areaRai: 24.6,
      areaSqWah: 9840,
      frontageMeters: 96,
      roadWidthMeters: 10,
      shapeEfficiencyScore: 79,
      ownershipComplexity: "singleOwner",
    },
    planning: {
      zoningCode: "ย.3",
      zoningDescription: "ที่อยู่อาศัยหนาแน่นน้อย",
      far: 2.5,
      buildabilityScore: 78,
      infrastructureReadinessScore: 73,
      allowableProductTypes: ["singleDetached", "townhome"],
      gisLayerIds: ["zoning-npt-residential", "flood-repeat-west"],
    },
    accessibility: {
      distanceToMassTransitMeters: 4200,
      distanceToExpresswayKm: 6.8,
      distanceToCbdKm: 28,
      driveTimeToCbdMinutes: 54,
    },
    market: {
      primaryCatchment: "Salaya, Phutthamonthon, western university cluster",
      targetSegments: ["midMarket", "upperMid"],
      estimatedResidentialPricePerSqm: 62000,
      demandDepthScore: 71,
    },
    financials: {
      askingPricePerSqWah: 87500,
      targetLandCostPerSqWah: 96000,
      estimatedGrossMarginPct: 27,
      capexComplexityScore: 70,
    },
    risk: {
      flood: "medium",
      legal: "low",
      environmental: "medium",
      communityPolitical: "low",
      criticalFlags: ["ต้องยืนยันระดับถนนและ drainage"],
    },
    controlStatus: "landBank",
    tags: ["hold", "western-growth", "campus-demand"],
  },
  {
    id: "AP-LAND-PTT-031",
    name: "รังสิต - คลอง 3",
    geometry: polygonAround(14.0004, 100.6594, 0.0048, 0.005),
    location: {
      district: "คลองหลวง",
      province: "ปทุมธานี",
      coordinates: { latitude: 14.0004, longitude: 100.6594 },
      strategicCorridor: "North Campus",
      metroZone: "periUrban",
    },
    site: {
      areaRai: 18.2,
      areaSqWah: 7280,
      frontageMeters: 58,
      roadWidthMeters: 8,
      shapeEfficiencyScore: 73,
      ownershipComplexity: "fragmentedOwners",
    },
    planning: {
      zoningCode: "ย.4",
      zoningDescription: "ที่อยู่อาศัยหนาแน่นน้อยถึงปานกลาง",
      far: 3,
      buildabilityScore: 76,
      infrastructureReadinessScore: 68,
      allowableProductTypes: ["townhome", "singleDetached"],
      gisLayerIds: ["zoning-ptt-residential", "flood-repeat-north"],
      constraintNotes: ["ต้องตรวจสอบภาระทางเข้าและระดับน้ำท่วมซ้ำซาก"],
    },
    accessibility: {
      distanceToMassTransitMeters: 5200,
      distanceToExpresswayKm: 5.4,
      distanceToCbdKm: 33,
      driveTimeToCbdMinutes: 62,
    },
    market: {
      primaryCatchment: "Rangsit, Khlong Luang, university corridor",
      targetSegments: ["affordable", "midMarket"],
      estimatedResidentialPricePerSqm: 54000,
      demandDepthScore: 76,
    },
    financials: {
      askingPricePerSqWah: 134500,
      targetLandCostPerSqWah: 108000,
      estimatedGrossMarginPct: 21,
      capexComplexityScore: 58,
    },
    risk: {
      flood: "high",
      legal: "medium",
      environmental: "medium",
      communityPolitical: "low",
      criticalFlags: ["ราคาเสนอสูงกว่า benchmark", "flood mitigation ต้องชัดเจน"],
    },
    controlStatus: "opportunity",
    tags: ["price-sensitive", "watchlist"],
  },
];

export const sampleCompetitors: CompetitorProject[] = [
  {
    id: "COMP-IDEO-R9",
    name: "IDEO Rama 9",
    developer: "Ananda",
    productType: "condominium",
    segment: "upperMid",
    location: {
      district: "ห้วยขวาง",
      province: "กรุงเทพฯ",
      coordinates: { latitude: 13.7547, longitude: 100.5738 },
    },
    units: 1246,
    launchedYear: 2024,
    salesRatePct: 78,
    averagePricePerSqm: 168000,
    distanceToMassTransitMeters: 420,
    status: "selling",
  },
  {
    id: "COMP-NUE-R9",
    name: "Nue District R9",
    developer: "Noble",
    productType: "condominium",
    segment: "midMarket",
    location: {
      district: "ห้วยขวาง",
      province: "กรุงเทพฯ",
      coordinates: { latitude: 13.7616, longitude: 100.5667 },
    },
    units: 1410,
    launchedYear: 2025,
    salesRatePct: 69,
    averagePricePerSqm: 142000,
    status: "selling",
  },
  {
    id: "COMP-ORIGIN-BANGNA",
    name: "Origin Place Bangna",
    developer: "Origin",
    productType: "condominium",
    segment: "midMarket",
    location: {
      district: "บางนา",
      province: "กรุงเทพฯ",
      coordinates: { latitude: 13.6599, longitude: 100.6219 },
    },
    units: 742,
    launchedYear: 2025,
    salesRatePct: 72,
    averagePricePerSqm: 112000,
    status: "selling",
  },
  {
    id: "COMP-NARASIRI-BANGNA",
    name: "Narasiri Bangna",
    developer: "Sansiri",
    productType: "singleDetached",
    segment: "luxury",
    location: {
      district: "บางพลี",
      province: "สมุทรปราการ",
      coordinates: { latitude: 13.6718, longitude: 100.6371 },
    },
    units: 184,
    launchedYear: 2023,
    salesRatePct: 66,
    averagePricePerSqm: 79000,
    status: "selling",
  },
  {
    id: "COMP-SALAYA-PARK",
    name: "Perfect Park Salaya",
    developer: "Property Perfect",
    productType: "singleDetached",
    segment: "midMarket",
    location: {
      district: "พุทธมณฑล",
      province: "นครปฐม",
      coordinates: { latitude: 13.7907, longitude: 100.3172 },
    },
    units: 420,
    launchedYear: 2022,
    salesRatePct: 58,
    averagePricePerSqm: 52000,
    status: "selling",
  },
  {
    id: "COMP-BRITANIA-RANGSIT",
    name: "Britania Rangsit",
    developer: "Britania",
    productType: "townhome",
    segment: "midMarket",
    location: {
      district: "คลองหลวง",
      province: "ปทุมธานี",
      coordinates: { latitude: 14.008, longitude: 100.6529 },
    },
    units: 360,
    launchedYear: 2023,
    salesRatePct: 52,
    averagePricePerSqm: 46000,
    status: "selling",
  },
  {
    id: "COMP-ANASIRI-RANGSIT",
    name: "Anasiri Rangsit",
    developer: "Sansiri",
    productType: "townhome",
    segment: "upperMid",
    location: {
      district: "คลองหลวง",
      province: "ปทุมธานี",
      coordinates: { latitude: 13.9928, longitude: 100.6695 },
    },
    units: 274,
    launchedYear: 2024,
    salesRatePct: 49,
    averagePricePerSqm: 51000,
    status: "selling",
  },
];

export const sampleMarketSignals: MarketSignal[] = [
  {
    id: "MKT-HUAIKHWANG-CONDO",
    district: "ห้วยขวาง",
    province: "กรุงเทพฯ",
    productType: "condominium",
    segment: "upperMid",
    period: "2026-Q2",
    source: "Internal research + market comp",
    demandIndex: 89,
    absorptionUnitsPerMonth: 54,
    priceGrowthPctYoY: 4.8,
    inventoryMonths: 13,
    confidence: 0.88,
  },
  {
    id: "MKT-BANGNA-MIX",
    district: "บางนา",
    province: "กรุงเทพฯ",
    segment: "midMarket",
    period: "2026-Q2",
    source: "Sales survey + property portal benchmark",
    demandIndex: 82,
    absorptionUnitsPerMonth: 36,
    priceGrowthPctYoY: 3.2,
    inventoryMonths: 18,
    confidence: 0.82,
  },
  {
    id: "MKT-NPT-LOWRISE",
    district: "นครชัยศรี",
    province: "นครปฐม",
    productType: "singleDetached",
    segment: "midMarket",
    period: "2026-Q2",
    source: "Broker survey + internal sales intelligence",
    demandIndex: 69,
    absorptionUnitsPerMonth: 14,
    priceGrowthPctYoY: 1.7,
    inventoryMonths: 22,
    confidence: 0.72,
  },
  {
    id: "MKT-PTT-TOWNHOME",
    district: "คลองหลวง",
    province: "ปทุมธานี",
    productType: "townhome",
    segment: "midMarket",
    period: "2026-Q2",
    source: "Market comp desk research",
    demandIndex: 74,
    absorptionUnitsPerMonth: 20,
    priceGrowthPctYoY: 0.6,
    inventoryMonths: 31,
    confidence: 0.69,
  },
];

export const sampleRiskSignals: RiskSignal[] = [
  {
    id: "RISK-RAMA9-EASEMENT",
    parcelId: "AP-LAND-BNK-014",
    type: "legal",
    severity: 2,
    probability: 0.45,
    mitigatable: true,
    description: "ต้องตรวจสอบภาระจำยอมและเงื่อนไขทางเข้า",
  },
  {
    id: "RISK-SALAYA-FLOOD",
    parcelId: "AP-LAND-NPT-006",
    type: "flood",
    severity: 3,
    probability: 0.52,
    mitigatable: true,
    description: "พื้นที่ต้องประเมินระดับถมดินและ drainage capacity",
  },
  {
    id: "RISK-RANGSIT-FLOOD",
    parcelId: "AP-LAND-PTT-031",
    type: "flood",
    severity: 4,
    probability: 0.7,
    mitigatable: true,
    description: "มี flood recurrence signal และต้องทดสอบ feasibility หลัง mitigation",
  },
];

export const sampleGisLayers: GISLayer[] = [
  {
    id: "zoning-bkk-commercial",
    name: "BMA Commercial Zoning",
    type: "zoning",
    province: "กรุงเทพฯ",
    attributes: { source: "BMA planning", version: "draft-2026", far: 8 },
  },
  {
    id: "transit-mrt-blue",
    name: "MRT/BTS Transit Catchment",
    type: "transport",
    province: "กรุงเทพฯ",
    attributes: { source: "Internal GIS", catchmentMeters: 800 },
  },
  {
    id: "flood-repeat-north",
    name: "Flood Recurrence North Metro",
    type: "flood",
    province: "ปทุมธานี",
    attributes: { source: "GISTDA derived layer", recurrence: "2011-2023" },
  },
];

export const sampleLandParcels = sampleParcels;
export const sampleCompetitorProjects = sampleCompetitors;
export const sampleGISLayers = sampleGisLayers;
